encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 0

group-channel-connections-config:
  caCert: classpath:ca.crt
  sslCert: classpath:node.crt
  sslKey: classpath:node.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 127.0.0.1:20200 # node listen_ip:channel_listen_port

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: fisco # agency name

accounts:
  pem-file: 0xcdcce60801c0a2e6bb534322c32ae528b9dec8d2.pem
